/**
 * Nunu Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse from './model/GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse';
import GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponseData from './model/GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponseData';
import GithubComGoNunuNunuLayoutAdvancedApiV1LoginRequest from './model/GithubComGoNunuNunuLayoutAdvancedApiV1LoginRequest';
import GithubComGoNunuNunuLayoutAdvancedApiV1LoginResponse from './model/GithubComGoNunuNunuLayoutAdvancedApiV1LoginResponse';
import GithubComGoNunuNunuLayoutAdvancedApiV1LoginResponseData from './model/GithubComGoNunuNunuLayoutAdvancedApiV1LoginResponseData';
import GithubComGoNunuNunuLayoutAdvancedApiV1RegisterRequest from './model/GithubComGoNunuNunuLayoutAdvancedApiV1RegisterRequest';
import GithubComGoNunuNunuLayoutAdvancedApiV1Response from './model/GithubComGoNunuNunuLayoutAdvancedApiV1Response';
import GithubComGoNunuNunuLayoutAdvancedApiV1UpdateProfileRequest from './model/GithubComGoNunuNunuLayoutAdvancedApiV1UpdateProfileRequest';
import DefaultApi from './api/DefaultApi';


/**
* This is a sample server celler server..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var NunuExampleApi = require('index'); // See note below*.
* var xxxSvc = new NunuExampleApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new NunuExampleApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new NunuExampleApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new NunuExampleApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse model constructor.
     * @property {module:model/GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse}
     */
    GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse,

    /**
     * The GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponseData model constructor.
     * @property {module:model/GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponseData}
     */
    GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponseData,

    /**
     * The GithubComGoNunuNunuLayoutAdvancedApiV1LoginRequest model constructor.
     * @property {module:model/GithubComGoNunuNunuLayoutAdvancedApiV1LoginRequest}
     */
    GithubComGoNunuNunuLayoutAdvancedApiV1LoginRequest,

    /**
     * The GithubComGoNunuNunuLayoutAdvancedApiV1LoginResponse model constructor.
     * @property {module:model/GithubComGoNunuNunuLayoutAdvancedApiV1LoginResponse}
     */
    GithubComGoNunuNunuLayoutAdvancedApiV1LoginResponse,

    /**
     * The GithubComGoNunuNunuLayoutAdvancedApiV1LoginResponseData model constructor.
     * @property {module:model/GithubComGoNunuNunuLayoutAdvancedApiV1LoginResponseData}
     */
    GithubComGoNunuNunuLayoutAdvancedApiV1LoginResponseData,

    /**
     * The GithubComGoNunuNunuLayoutAdvancedApiV1RegisterRequest model constructor.
     * @property {module:model/GithubComGoNunuNunuLayoutAdvancedApiV1RegisterRequest}
     */
    GithubComGoNunuNunuLayoutAdvancedApiV1RegisterRequest,

    /**
     * The GithubComGoNunuNunuLayoutAdvancedApiV1Response model constructor.
     * @property {module:model/GithubComGoNunuNunuLayoutAdvancedApiV1Response}
     */
    GithubComGoNunuNunuLayoutAdvancedApiV1Response,

    /**
     * The GithubComGoNunuNunuLayoutAdvancedApiV1UpdateProfileRequest model constructor.
     * @property {module:model/GithubComGoNunuNunuLayoutAdvancedApiV1UpdateProfileRequest}
     */
    GithubComGoNunuNunuLayoutAdvancedApiV1UpdateProfileRequest,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
