/* tslint:disable */
/* eslint-disable */
/**
 * Nunu Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";


import { DefaultApi, Configuration } from './api'; // 引入生成的 API 类和配置

// 动态设置后端地址
const basePath = process.env.VUE_APP_BASE_API || 'http://localhost:8000';

// 创建全局配置实例
const config = new Configuration({ basePath });

// 创建全局 API 客户端实例
const apiClient = new DefaultApi(config);

// 设置 Axios 请求拦截器：自动注入 Token
apiClient.axios.interceptors.request.use((requestConfig) => {
  const token = localStorage.getItem('accessToken'); // 从 localStorage 获取 Token
  if (token) {
    requestConfig.headers.Authorization = `Bearer ${token}`; // 注入 Authorization 头部
  }
  return requestConfig;
});

export default apiClient; // 导出全局实例