/**
 * Nunu Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponseData from './GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponseData';

/**
 * The GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse model module.
 * @module model/GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse
 * @version 1.0.0
 */
class GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse {
    /**
     * Constructs a new <code>GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse</code>.
     * @alias module:model/GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse
     */
    constructor() { 
        
        GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse} obj Optional instance to populate.
     * @return {module:model/GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse} The populated <code>GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponseData.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponseData.validateJSON(data['data']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}



/**
 * @member {Number} code
 */
GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse.prototype['code'] = undefined;

/**
 * @member {module:model/GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponseData} data
 */
GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse.prototype['data'] = undefined;

/**
 * @member {String} message
 */
GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse.prototype['message'] = undefined;






export default GithubComGoNunuNunuLayoutAdvancedApiV1GetProfileResponse;

